### ISSUE TITLE
The JIRA issue shall show the type (ICON is ok as well)

### ISSUE THREAD

**Issue by KarateJB** [YiHaoLin1207/jirapoker.web#2]
If the issue can show what card type it is (like putting an icon on the following red block), we can identify it in one look. 

![image](https://user-images.githubusercontent.com/13954352/71945539-0f863b00-3202-11ea-894f-4dd957d35a2e.png)

**Comment by YiHaoLin1207** [comment]
good advice! Some body will do this task

**Comment by YiHaoLin1207** [comment]
Done
